### ISSUE TITLE
Curl can't be installed in julia 0.4.6

### ISSUE THREAD

**Issue by ghost** [forio/Curl.jl#14]
Excuse me , Curl can't be installed in julia 0.4.6
![curladdfailure](https://cloud.githubusercontent.com/assets/18660347/16615936/843ebc12-43ac-11e6-9d47-ad8c2c21ac85.png)

**Comment by tkelman** [comment]
This package is deprecated.

**Comment by WestleyArgentum** [comment]
@The-Kite-Runner try using https://github.com/JuliaWeb/Requests.jl
