### ISSUE TITLE
Register as a package

### ISSUE THREAD

**Issue by ViralBShah** [forio/Curl.jl#2]
Given the interest in curl wrappers as dicussed here - https://groups.google.com/forum/?fromgroups=#!topic/julia-dev/ax9OVSBA_OE, can we register Curl.jl as a package in METADATA?

**Comment by ViralBShah** [comment]
Cc: @amitmurthy

**Comment by adambom** [comment]
That's cool with us. We just wanted to make sure it was ready before we submitted it.

It should be good to go. The only known issues are that we're still missing support for some HTTP verbs (put, options, patch...) and #1  which seems to happen on snow leopard.

We also need to figure out a way of bundling libcurl in case you don't have it.

**Comment by pauladam** [comment]
@ViralBShah Yea that would be great, do we need to do anything?

**Comment by ViralBShah** [comment]
You need to register it in METADATA by creating a pull request. I believe that libcurl is only a problem on Windows.

Even if it is work in progress, it is good to register it in METADATA, so that others can know about it and comment on design, contribute, etc.

**Comment by adambom** [comment]
Pull request sent.

**Comment by ViralBShah** [comment]
Thanks.
