### ISSUE TITLE
unsafe_ref is deprecated, use unsafe_load instead.

### ISSUE THREAD

**Issue by ordovician** [forio/Curl.jl#7]
When running `Curl.get("http://jsonip.com").text` I get the message:

```
WARNING: unsafe_ref is deprecated, use unsafe_load instead.
 in gen_write_cb at /Users/erikengheim/.julia/Curl/src/Curl.jl:75
```

**Comment by pauladam** [comment]
I believe this is fixed by 2e3c3fb04d51470c2d59f5f90cea0717b0edd314, have you updated and tried again?

**Comment by WestleyArgentum** [comment]
I think we needed to bump the sha in Metadata. I submitted a pull request: https://github.com/JuliaLang/METADATA.jl/pull/270

Once someone does a remaster it should be available with `Pkg.update()`

**Comment by ordovician** [comment]
@pauladam I tried again. Looks fine now.
