### ISSUE TITLE
Deprecate in favor of libCurl.jl

### ISSUE THREAD

**Issue by adambom** [forio/Curl.jl#9]
Need to push a new version the prints a deprecated message. Also make a note in the README.

**Comment by garborg** [comment]
Guessing this hasn't happened because LibCurl.jl doesn't match Curl.jl's high-level functionality?

I was going to add a fr for a get method with a params argument (or exposing the %-escaping), but I'm not sure what the roadmap for these packages is.

**Comment by pauladam** [comment]
Hey @garborg , I'll let @WestleyArgentum comment on what Forio's current use or plans for Curl.jl are but personally I wouldnt be against that functionality as long as it conformed reasonably well to the existing api patterns.

**Comment by WestleyArgentum** [comment]
I recently tried to get input from the maintainers of the other Julia http client packages [here](https://groups.google.com/forum/#!topic/julia-users/pZNqzfxtgvo), but no luck so far.

I'd say, if you want something, make it happen. I'm more than happy to accept pull requests, and it sounds like @pauladam is as well.

**Comment by garborg** [comment]
Sounds good. And thanks for the quick responses.
